# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afd2e95edc61bf07a769d63e00f7def6412b99130cae422a235c88480ce4b0d6c28e227364494a23c050a8a8be998c02e6cf48dbc51f3099ecf1393eec38ca87

test:
  secret_key_base: a74caebaeea69b9e15bd1491c8610c440ee522a1d0def57e737ee53a776f632f9aefc3020f981cdb46ae6574e37a41aa6b550eaf6307ed89d68a2841ff3f83d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
